
version: '3.8'

services:
  postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    image: postgres:latest
    container_name: shopping_website_db
    environment:
      POSTGRES_DB: shopping_website_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
volumes:
  postgres_data:

